package net.subtotalcamp875.silverlight.entity.custom;

import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.LivingEntity;
import net.minecraft.entity.mob.SkeletonEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.entity.projectile.thrown.ThrownItemEntity;
import net.minecraft.item.Item;
import net.minecraft.util.hit.BlockHitResult;
import net.minecraft.util.hit.EntityHitResult;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.subtotalcamp875.silverlight.entity.ModEntities;
import net.subtotalcamp875.silverlight.item.ModItems;

public class DeathsBombEntity extends ThrownItemEntity {
    public DeathsBombEntity(EntityType<? extends ThrownItemEntity> entityType, World world) {
        super(entityType, world);
    }

    public DeathsBombEntity(LivingEntity livingEntity, World world) {
        super(ModEntities.DEATHS_BOMB_PROJECTILE, livingEntity, world);
    }

    @Override
    protected Item getDefaultItem() {
        return ModItems.DEATHS_BOMB;
    }

    @Override
    protected void onBlockHit(BlockHitResult blockHitResult) {
        if (!this.getWorld().isClient) {
            BlockPos blockPos = blockHitResult.getBlockPos();
            World world = this.getWorld();


            SkeletonEntity skeletonEntity = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity1 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity2 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity3 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity4 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity5 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity6 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity7 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity8 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity9 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity10 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity11 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity12 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity13 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity14 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity15 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity16 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity17 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity18 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity19 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity20 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity21 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity22 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity23 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity24 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity25 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity26 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity27 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity28 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity29 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity31 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity32 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity33 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity34 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity35 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity36 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity37 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity38 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity39 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity30 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity41 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity42 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity43 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity44 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity45 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity46 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity47 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity48 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity49 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity40 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity51 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity52 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity53 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity54 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity55 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity56 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity57 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity58 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity59 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity50 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity61 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity62 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity63 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity64 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity65 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity66 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity67 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity68 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity69 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity60 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity71 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity72 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity73 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity74 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity75 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity76 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity77 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity78 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity79 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity70 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity81 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity82 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity83 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity84 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity85 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity86 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity87 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity88 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity89 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity80 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity91 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity92 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity93 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity94 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity95 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity96 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity97 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity98 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity99 = new SkeletonEntity(EntityType.SKELETON, world);
            SkeletonEntity skeletonEntity90 = new SkeletonEntity(EntityType.SKELETON, world);
            skeletonEntity.setPosition(blockPos.toCenterPos());
            skeletonEntity1.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity2.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity3.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity4.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity5.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity6.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity7.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity8.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity9.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity10.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity11.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity12.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity13.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity14.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity15.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity16.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity17.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity18.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity19.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity20.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity21.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity22.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity23.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity24.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity25.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity26.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity27.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity28.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity29.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity30.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity31.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity32.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity33.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity34.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity35.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity36.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity37.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity38.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity39.setPosition(blockPos.add(world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity40.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity41.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity42.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity43.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity44.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity45.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity46.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity47.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity48.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity49.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity50.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity51.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity52.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity53.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity54.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity55.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity56.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity57.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity58.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity59.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity60.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity61.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity62.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity63.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity64.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity65.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity66.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity67.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity68.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity69.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity70.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity71.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity72.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity73.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity74.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity75.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity76.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity77.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity78.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity79.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity80.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity81.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity82.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity83.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity84.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity85.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity86.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity87.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity88.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity89.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity90.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity91.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity92.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity93.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity94.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity95.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity96.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity97.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity98.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());
            skeletonEntity99.setPosition(blockPos.add(-world.getRandom().nextInt(8), world.getRandom().nextInt(8), -world.getRandom().nextInt(8)).toCenterPos());

            world.spawnEntity(skeletonEntity);
            world.spawnEntity(skeletonEntity1);
            world.spawnEntity(skeletonEntity2);
            world.spawnEntity(skeletonEntity3);
            world.spawnEntity(skeletonEntity4);
            world.spawnEntity(skeletonEntity5);
            world.spawnEntity(skeletonEntity6);
            world.spawnEntity(skeletonEntity7);
            world.spawnEntity(skeletonEntity8);
            world.spawnEntity(skeletonEntity9);
            world.spawnEntity(skeletonEntity10);
            world.spawnEntity(skeletonEntity11);
            world.spawnEntity(skeletonEntity12);
            world.spawnEntity(skeletonEntity13);
            world.spawnEntity(skeletonEntity14);
            world.spawnEntity(skeletonEntity15);
            world.spawnEntity(skeletonEntity16);
            world.spawnEntity(skeletonEntity17);
            world.spawnEntity(skeletonEntity18);
            world.spawnEntity(skeletonEntity19);
            world.spawnEntity(skeletonEntity20);
            world.spawnEntity(skeletonEntity21);
            world.spawnEntity(skeletonEntity22);
            world.spawnEntity(skeletonEntity23);
            world.spawnEntity(skeletonEntity24);
            world.spawnEntity(skeletonEntity25);
            world.spawnEntity(skeletonEntity26);
            world.spawnEntity(skeletonEntity27);
            world.spawnEntity(skeletonEntity28);
            world.spawnEntity(skeletonEntity29);
            world.spawnEntity(skeletonEntity30);
            world.spawnEntity(skeletonEntity31);
            world.spawnEntity(skeletonEntity32);
            world.spawnEntity(skeletonEntity33);
            world.spawnEntity(skeletonEntity34);
            world.spawnEntity(skeletonEntity35);
            world.spawnEntity(skeletonEntity36);
            world.spawnEntity(skeletonEntity37);
            world.spawnEntity(skeletonEntity38);
            world.spawnEntity(skeletonEntity39);
            world.spawnEntity(skeletonEntity40);
            world.spawnEntity(skeletonEntity41);
            world.spawnEntity(skeletonEntity42);
            world.spawnEntity(skeletonEntity43);
            world.spawnEntity(skeletonEntity44);
            world.spawnEntity(skeletonEntity45);
            world.spawnEntity(skeletonEntity46);
            world.spawnEntity(skeletonEntity47);
            world.spawnEntity(skeletonEntity48);
            world.spawnEntity(skeletonEntity49);
            world.spawnEntity(skeletonEntity50);
            world.spawnEntity(skeletonEntity51);
            world.spawnEntity(skeletonEntity52);
            world.spawnEntity(skeletonEntity53);
            world.spawnEntity(skeletonEntity54);
            world.spawnEntity(skeletonEntity55);
            world.spawnEntity(skeletonEntity56);
            world.spawnEntity(skeletonEntity57);
            world.spawnEntity(skeletonEntity58);
            world.spawnEntity(skeletonEntity59);
            world.spawnEntity(skeletonEntity60);
            world.spawnEntity(skeletonEntity61);
            world.spawnEntity(skeletonEntity62);
            world.spawnEntity(skeletonEntity63);
            world.spawnEntity(skeletonEntity64);
            world.spawnEntity(skeletonEntity65);
            world.spawnEntity(skeletonEntity66);
            world.spawnEntity(skeletonEntity67);
            world.spawnEntity(skeletonEntity68);
            world.spawnEntity(skeletonEntity69);
            world.spawnEntity(skeletonEntity70);
            world.spawnEntity(skeletonEntity71);
            world.spawnEntity(skeletonEntity72);
            world.spawnEntity(skeletonEntity73);
            world.spawnEntity(skeletonEntity74);
            world.spawnEntity(skeletonEntity75);
            world.spawnEntity(skeletonEntity76);
            world.spawnEntity(skeletonEntity77);
            world.spawnEntity(skeletonEntity78);
            world.spawnEntity(skeletonEntity79);
            world.spawnEntity(skeletonEntity80);
            world.spawnEntity(skeletonEntity81);
            world.spawnEntity(skeletonEntity82);
            world.spawnEntity(skeletonEntity83);
            world.spawnEntity(skeletonEntity84);
            world.spawnEntity(skeletonEntity85);
            world.spawnEntity(skeletonEntity86);
            world.spawnEntity(skeletonEntity87);
            world.spawnEntity(skeletonEntity88);
            world.spawnEntity(skeletonEntity89);
            world.spawnEntity(skeletonEntity90);
            world.spawnEntity(skeletonEntity91);
            world.spawnEntity(skeletonEntity92);
            world.spawnEntity(skeletonEntity93);
            world.spawnEntity(skeletonEntity94);
            world.spawnEntity(skeletonEntity95);
            world.spawnEntity(skeletonEntity96);
            world.spawnEntity(skeletonEntity97);
            world.spawnEntity(skeletonEntity98);
            world.spawnEntity(skeletonEntity99);

            this.discard();
        }
        super.onBlockHit(blockHitResult);
    }


    public void test(PlayerEntity livingEntity) {
        livingEntity.addCommandTag("Silverlight Deaths Bomb Entity test");
    }
}
